#!/bin/sh

## Set up variables we use
RSYNC='/usr/bin/rsync'
RS_OPT="-avSHP  --numeric-ids"
RS_DEADLY="--delete --delete-excluded --delete-delay --delay-updates"
CENT_EXCLUDES="--exclude=iso --exclude=kickstart --exclude=images --exclude=debug --exclude=source"

SERVER=centos-master01.rdu3.fedoraproject.org

## Mirror CentOS-9-Stream

RSYNC_DESTDIR=/mnt/fedora/app/fi-repo/centos/centos-9-stream/
RSYNC_MOD="CentOS-Stream-Ref/9-stream/"

mkdir -p ${RSYNC_DESTDIR}


${RSYNC} ${RS_OPT} ${RS_DEADLY} ${CENT_EXCLUDES} ${SERVER}::${RSYNC_MOD} ${RSYNC_DESTDIR}
