#!/bin/sh

## Set up variables we use
RSYNC='/usr/bin/rsync'
RS_OPT="-avSHP --numeric-ids"
RS_DEADLY="--delete --delete-delay --delay-updates"
CENT_EXCLUDES="--exclude=isos --exclude=kickstart --exclude=images --exclude=debug"

SERVER=centos-master01.iad2.fedoraproject.org

## Mirror CentOS-10-Stream

RSYNC_DESTDIR=/mnt/fedora/app/fi-repo/centos/centos-10/
RSYNC_MOD="CentOS-Stream-Ref/10-stream/"

mkdir -p ${RSYNC_DESTDIR}

${RSYNC} ${RS_OPT} ${RS_DEADLY} ${CENT_EXCLUDES} ${SERVER}::${RSYNC_MOD} ${RSYNC_DESTDIR}