#! /bin/sh

cat <<EOF >copr-ping.spec
%global		_source_filedigest_algorithm md5

Name:		copr-ping
Version:	$(date +"%Y%m%d_%H%M%S")
Release:	1%{?dist}
Summary:	A dummy package

Group:		NONE
License:	GPLv3+
URL:		http://example.com/

%if 0%{?rhel} && 0%{?rhel} <= 5
BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
%endif
Source0:	https://raw.githubusercontent.com/praiskup/quick-package/master/README.xz

%{!?_pkgdocdir: %global _pkgdocdir %{_docdir}/%{name}-%{version}}

%description
Description for the %name package that is used for various testing tasks.


%prep


%build


%install
rm -rf \$RPM_BUILD_ROOT
mkdir -p \$RPM_BUILD_ROOT/%{_pkgdocdir}
xz -d %{SOURCE0} --stdout > \$RPM_BUILD_ROOT/%{_pkgdocdir}/README


%clean
rm -rf \$RPM_BUILD_ROOT


%files
%dir %{_pkgdocdir}
%doc %{_pkgdocdir}/README

%changelog
* Thu Jun 05 2014 Pavel Raiskup <praiskup@redhat.com> - 0-1
- does nothing!
EOF

echo "DOES NOTHING" > README
xz README
