FROM quay.io/fedora/python-311:latest
LABEL \
    name="python-311-with-rust" \
    vendor="Fedora Infrastructure" \
    license="MIT"
USER root
# Add RPM-only modules
RUN dnf install -y python3-pyrpmmd
# Add Rust
RUN dnf install -y cargo
# Add Logrotate
RUN dnf install -y logrotate
USER 1001
