FROM quay.io/fedora/python-311:latest
LABEL \
    name="python-311-with-rust" \
    vendor="Fedora Infrastructure" \
    license="MIT"
USER root
# Add RPM-only modules, Rust, protoc and logrotate
RUN dnf install -y python3-pyrpmmd cargo protobuf-compiler logrotate
USER 1001
